User Profile
R-Aranda/band-reviewer pull request #10
Opened 2022-08-09 18:03 UTC by luketaylor9000

Created User Profile component to display user information.

Created migrations for adding username and photo column and updated serializer accordingly.

Updated review serializer to account for user association. 

Set up associations between user, artist, and review.

Added user object param to review controller.

Created upload profile_photo feature to have user profile_photo stored in AWS S3.

2022-08-09 18:07 UTC, nwalberts requested changes

2022-08-09 18:07 UTC, nwalberts commented on app/controllers/api/v1/users_controller.rb
> +    render json: user
we can combine this into one lin!

2022-08-09 18:07 UTC, nwalberts commented on app/javascript/react/components/Users/UserPage.js
> +  }, []);
add a space after this useEffect

2022-08-09 18:07 UTC, nwalberts commented on app/controllers/api/v1/users_controller.rb
> +  end
I dont think this endpoint is being used? delete it!

2022-08-09 19:45 UTC, nwalberts requested changes

2022-08-09 19:45 UTC, nwalberts commented on app/controllers/api/v1/reviews_controller.rb
> +    binding.pry
ACCKKK BAD

2022-08-09 19:45 UTC, nwalberts commented on app/controllers/api/v1/reviews_controller.rb
> +    review.user_id = user.id
in rails we can conver to 
`review.user = user`

But you shouldnt need a `user` method. Just use `current_user`!!!

2022-08-09 19:45 UTC, nwalberts commented on app/javascript/react/components/Reviews/ReviewTile.js
> +      <p>User Id: {user_id}</p>
why...in the world would we need to see their user_id? username or even email I can understand, but id?

2022-08-09 19:45 UTC, nwalberts commented on app/javascript/react/components/Users/UserPage.js
> +  const [profilePhoto, setProfilePhoto] = useState([])
I know they are nested differently, but can we try to combine these into one piece of state?

2022-08-09 19:45 UTC, nwalberts commented on app/javascript/react/components/Users/UserPage.js
> +    </div>
since this div isnt doing anything, we should replace it with a React Fragment 
```
<>
   <p> hello </p>
</>
```

2022-08-09 19:45 UTC, nwalberts commented on db/migrate/20220809144453_add_profile_photo_to_users.rb
> +  end
um, do we need both of these photo migrations....?

2022-08-09 19:45 UTC, nwalberts commented on db/schema.rb
> +>>>>>>> user_page
AACCKCKKK VERY BAD!!!  Resolve these merge markers!

2022-08-09 19:45 UTC, nwalberts commented on db/schema.rb
> +>>>>>>> user_page
SADDDD

2022-08-09 19:45 UTC, nwalberts commented on spec/controllers/api/v1/users_controller_spec.rb
> +      expect(return_json["user"]["email"]).to eq user.email
wait...but we get MORE than just the email right? update accordingly!

2022-08-09 20:55 UTC, luketaylor9000 commented on db/schema.rb
> +>>>>>>> user_page
No you

2022-08-11 16:12 UTC, luketaylor9000 commented
Also fixed the issues with Devise in the Controller Specs

2022-08-11 18:16 UTC, merged