Artist show page
R-Aranda/band-reviewer pull request #2
Opened 2022-08-02 19:25 UTC by R-Aranda

-Added an artist show page component
-Added artist show page route to react router
-Added some foundation and styling to the show page
-Added controller testing to the artist show page

2022-08-02 21:30 UTC, nwalberts requested changes

2022-08-02 21:30 UTC, nwalberts commented on app/javascript/react/components/Artists/ArtistShowPage.js
> +            website={artist.website}
convention is to indent all props in. Indent in lines 30 to 34

2022-08-02 21:30 UTC, nwalberts commented on app/javascript/react/components/Artists/ArtistTopSection.js
> +                        </div>
unless you plan on having this adorable kitten image in your website forever, remove this until you decide on something more permanent!

2022-08-02 21:30 UTC, nwalberts commented on app/javascript/react/components/Artists/ArtistTopSection.js
> +                            <p> <a href="#" className="read-more"> Read More on their website </a> </p>
hmmm, this link to this website will actually have to be REAL. and working. Update your seeds file to seed artists that exist with real website links. Then, make sure that this is not hard-coded to go nowhere

2022-08-02 21:30 UTC, nwalberts commented on app/javascript/react/components/Artists/ArtistTopSection.js
> +                                <p> Average Rating: /5 </p>
I would remove this average rating for now. Its technically an unfinished feature. You can always add it in later

2022-08-02 21:30 UTC, nwalberts commented on config/routes.rb
> +  get "*path", to:"homes#index", via: :all
as mentioned earlier, I dont want folks using the wild-card path. Instead, for any new paths you should add, you should be adding those explicitly

2022-08-02 21:30 UTC, nwalberts commented on db/seeds.rb
> +Artist.create(name: "Hole", bio: "Good band BUT I HATE COURTNEY LOVE!!!")
dope. Add their actual websites as well!

2022-08-02 21:30 UTC, nwalberts commented on spec/controllers/api/v1/artists_controller_spec.rb
> +  describe "GET#index" do
uh oh, this says get INDEX, but this tests is for the show

2022-08-03 14:48 UTC, devinrojas reviewed
-Updated and cleaned up all the comments you left
-Added websites to all of the seeded artists
-indented props in our  "Artist Top Section" 
-Improved controller test to have it GET the show page

2022-08-03 17:13 UTC, merged